server:
  port: 8188
  servlet:
    context-path: /maintenance
location: img
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/maintenance
    username: **********
    password: **********
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: *************************************************
  lifetime: 36000000
